services:
  nginx:
    image: nginx:alpine
    ports:
      - "9090:80"  # porta do host : porta do container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # sobrescreve a config padrão
      - ./html:/usr/share/nginx/html        # mapeia nosso html para o diretório raiz e tudo que sera servido pelo nginx nesse projeto esta aqui
